import json

from sqlalchemy.orm import Session

from app.models.bus import Bus, BusStatus
from app.models.route import Route
from app.redis import redis_client


def get_available_buses(
    db: Session,
    route_id: int
):
    route = (
        db.query(Route)
        .filter(Route.route_id == route_id)
        .first()
    )

    if not route:
        raise ValueError("Route not found")

    buses = (
        db.query(Bus)
        .filter(
            Bus.status == BusStatus.ACTIVE
        )
        .order_by(Bus.bus_number)
        .all()
    )

    return buses


def create_assignment(
    db: Session,
    poll_id: str,
    route_id: int,
    bus_numbers: list[int]
):
    # Make sure route exists
    route = (
        db.query(Route)
        .filter(Route.route_id == route_id)
        .first()
    )

    if not route:
        raise ValueError("Route not found")

    # Make sure poll exists
    poll_key = f"poll:{poll_id}:meta"

    if not redis_client.exists(poll_key):
        raise ValueError("Poll not found")

    # Get the headcount generated by the first poll
    headcount_key = (
        f"poll:{poll_id}:headcount:{route_id}"
    )

    headcount = int(
        redis_client.get(headcount_key) or 0
    )

    if headcount == 0:
        raise ValueError(
            "No students are travelling on this route"
        )

    # Remove duplicates
    bus_numbers = list(set(bus_numbers))

    # Fetch selected buses
    buses = (
        db.query(Bus)
        .filter(
            Bus.bus_number.in_(bus_numbers),
            Bus.status == BusStatus.ACTIVE
        )
        .all()
    )

    if len(buses) != len(bus_numbers):
        raise ValueError(
            "One or more selected buses are unavailable"
        )

    total_capacity = sum(
        bus.capacity
        for bus in buses
    )

    if total_capacity < headcount:
        raise ValueError(
            f"Insufficient capacity. "
            f"Required: {headcount}, "
            f"selected: {total_capacity}"
        )

    assignment_key = (
        f"assignment:{poll_id}:{route_id}"
    )

    assignment = {
        "poll_id": poll_id,
        "route_id": route_id,
        "bus_numbers": bus_numbers,
        "total_capacity": total_capacity,
        "headcount": headcount,
        "status": "DRAFT"
    }

    redis_client.set(
        assignment_key,
        json.dumps(assignment)
    )

    return assignment


def publish_assignment(
    poll_id: str,
    route_id: int
):
    assignment_key = (
        f"assignment:{poll_id}:{route_id}"
    )

    raw_assignment = redis_client.get(
        assignment_key
    )

    if not raw_assignment:
        raise ValueError(
            "Assignment not found"
        )

    assignment = json.loads(
        raw_assignment
    )

    if assignment["status"] == "PUBLISHED":
        raise ValueError(
            "Assignment already published"
        )

    assignment["status"] = "PUBLISHED"

    redis_client.set(
        assignment_key,
        json.dumps(assignment)
    )

    return assignment


def get_assignment(
    poll_id: str,
    route_id: int
):
    assignment_key = (
        f"assignment:{poll_id}:{route_id}"
    )

    raw_assignment = redis_client.get(
        assignment_key
    )

    if not raw_assignment:
        raise ValueError(
            "Assignment not found"
        )

    return json.loads(raw_assignment)