"""initial schema

Revision ID: 4266e0bfb944
Revises: 
Create Date: 2026-08-19 17:41:32.174770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4266e0bfb944'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('bus_number', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='busstatus'), nullable=False),
    sa.PrimaryKeyConstraint('bus_number'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_location', sa.String(length=255), nullable=False),
    sa.Column('end_location', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('bus_assignments',
    sa.Column('bus_number', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bus_number'], ['buses.bus_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bus_number', 'route_id')
    )
    op.create_table('departure_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('bus_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bus_number'], ['buses.bus_number'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('manager_id')
    )
    op.create_table('students',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('managers')
    op.drop_table('departure_statistics')
    op.drop_table('bus_assignments')
    op.drop_table('users')
    op.drop_table('routes')
    op.drop_table('buses')
    # ### end Alembic commands ###
